### ISSUE TITLE
Match

### ISSUE THREAD

**Issue by shankardevy** [nittin-shankar/MIC#3]
Attribute name | Type
--------------- | -----
Event | String
1st inning score | Integer
2nd inning score | Integer
Date | Date
Venue | Array:String
Player of the match | String
Umpires | String

**Comment by Nittinshankar** [comment]
Attribute name | Type
--------------- | -----
Event | String
1st inning score | Integer
2nd inning score | Integer
Date | Date
Venue | Array:String
Player of the match | String
Umpires | String
